services:
    postgres-db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: WarehouseDB
        ports:
            - 5432:5432
        networks:
            - services-network
        volumes:
            - postgres_data:/var/lib/postgresql/data 

    warehouseservice:
        image: ${DOCKER_REGISTRY-}warehouseservice
        build:
            context: .
            dockerfile: WarehouseService/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - services-network
        depends_on:
            - postgres-db

networks:
    services-network:    
        driver: bridge

volumes:
    postgres_data: